version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: myproject-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root # should put in environment IE:  ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"
